#!/bin/bash

        /Users/namsonnguyen/repo/am-14.0/src/am MaunaKea_SON_50.amc         180 GHz 420 GHz 10 MHz 1.289335381956981 rad 277 K 7.38905609893065         > /Users/namsonnguyen/repo/data/AM_data/SON50_delay_spectra/MaunaKea_Delay_Spectrum_1.281_2.000.out         2> /Users/namsonnguyen/repo/data/AM_data/SON50_delay_spectra/MaunaKea_Delay_Spectrum_1.281_2.000.err
        